___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

### Create an array of 10 zeros 

In [2]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
list = [5,5,5,5,5,5,5,5,5,5]
c=np.array(list)
c

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [9]:
d=np.arange(10,51)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [11]:
e = np.arange(10,51,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
m = np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
i = np.ones(9).reshape(3,3)
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [17]:
j = np.random.rand(2)
j

array([0.94249545, 0.1437603 ])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [25]:
k = np.random.rand(25)
k

array([0.93393714, 0.07229976, 0.231818  , 0.44908206, 0.75828217,
       0.40619252, 0.97021642, 0.06299627, 0.07125019, 0.62438712,
       0.35482911, 0.34681227, 0.41127462, 0.51418724, 0.68378975,
       0.32029008, 0.30916278, 0.91982209, 0.09384213, 0.07761557,
       0.00212174, 0.85402225, 0.12918368, 0.66125406, 0.85273455])

#### Create the following matrix:

In [26]:
list = [[1,2,3] , [4,5,6] , [7,8,9]]
ar1 = np.array(list)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
o = np.linspace(0,1,20)
o

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [4]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [6]:
list = [[12,13,14,15] , [17,18,19,20] , [22,23,24,25]
array = np.array(list)
array

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [7]:
array[1,3]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [8]:
array = np.arange(2,23,5).reshape(5,1)
array

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [9]:
array = np.arange(21,26)
array

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [10]:
array = np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])